export const SITUACOES_PADRAO = [
  'ENVIADA',
  'RECEBIDA',
  'EM_ANALISE',
  'EM_NEGOCIACAO',
  'CONTRATADA',
  'RECUSADA',
  'EXPIRADA',
  'CANCELADA',
  'CONTRATADA_COM_LINHA_BNDES',
  'CONTRATADA_COM_LINHAS_PROPRIAS',
  'CONTRATADA_COM_FIDC_BNDES',
  'CONTRATADA_BNDES_MICROCREDITO'
]
